# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class YOLOX(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(YOLOX, self).__init__()
        self.module_0 = py_nndct.nn.Input() #YOLOX::input_0(YOLOX::nndct_input_0)
        self.module_1 = py_nndct.nn.quant_input() #YOLOX::YOLOX/QuantStub[quant_in]/27470(YOLOX::nndct_quant_stub_1)
        self.module_2 = py_nndct.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/BaseConv[stem]/Conv2d[conv]/ret.5(YOLOX::nndct_conv2d_2)
        self.module_3 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/BaseConv[stem]/ReLU[act]/27501(YOLOX::nndct_relu_3)
        self.module_4 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=16, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.9(YOLOX::nndct_depthwise_conv2d_4)
        self.module_5 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/DWConv[0]/BaseConv[dconv]/ReLU[act]/27529(YOLOX::nndct_relu_5)
        self.module_6 = py_nndct.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.13(YOLOX::nndct_conv2d_6)
        self.module_7 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/DWConv[0]/BaseConv[pconv]/ReLU[act]/27557(YOLOX::nndct_relu_7)
        self.module_8 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv1]/Conv2d[conv]/ret.17(YOLOX::nndct_conv2d_8)
        self.module_9 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv1]/ReLU[act]/27585(YOLOX::nndct_relu_9)
        self.module_10 = py_nndct.nn.Conv2d(in_channels=32, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv2]/Conv2d[conv]/ret.21(YOLOX::nndct_conv2d_10)
        self.module_11 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv2]/ReLU[act]/27613(YOLOX::nndct_relu_11)
        self.module_12 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.25(YOLOX::nndct_conv2d_12)
        self.module_13 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/27641(YOLOX::nndct_relu_13)
        self.module_14 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=16, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.29(YOLOX::nndct_depthwise_conv2d_14)
        self.module_15 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/27669(YOLOX::nndct_relu_15)
        self.module_16 = py_nndct.nn.Conv2d(in_channels=16, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.33(YOLOX::nndct_conv2d_16)
        self.module_17 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/27697(YOLOX::nndct_relu_17)
        self.module_18 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/Add[sc_add]/ret.37(YOLOX::nndct_elemwise_add_18)
        self.module_19 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/Cat[cat]/ret.39(YOLOX::nndct_concat_19)
        self.module_20 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv3]/Conv2d[conv]/ret.41(YOLOX::nndct_conv2d_20)
        self.module_21 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark2]/Q_CSPLayer[1]/BaseConv[conv3]/ReLU[act]/27732(YOLOX::nndct_relu_21)
        self.module_22 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.45(YOLOX::nndct_depthwise_conv2d_22)
        self.module_23 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/DWConv[0]/BaseConv[dconv]/ReLU[act]/27760(YOLOX::nndct_relu_23)
        self.module_24 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.49(YOLOX::nndct_conv2d_24)
        self.module_25 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/DWConv[0]/BaseConv[pconv]/ReLU[act]/27788(YOLOX::nndct_relu_25)
        self.module_26 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv1]/Conv2d[conv]/ret.53(YOLOX::nndct_conv2d_26)
        self.module_27 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv1]/ReLU[act]/27816(YOLOX::nndct_relu_27)
        self.module_28 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv2]/Conv2d[conv]/ret.57(YOLOX::nndct_conv2d_28)
        self.module_29 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv2]/ReLU[act]/27844(YOLOX::nndct_relu_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.61(YOLOX::nndct_conv2d_30)
        self.module_31 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/27872(YOLOX::nndct_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.65(YOLOX::nndct_depthwise_conv2d_32)
        self.module_33 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/27900(YOLOX::nndct_relu_33)
        self.module_34 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.69(YOLOX::nndct_conv2d_34)
        self.module_35 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/27928(YOLOX::nndct_relu_35)
        self.module_36 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/Add[sc_add]/ret.73(YOLOX::nndct_elemwise_add_36)
        self.module_37 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/BaseConv[conv1]/Conv2d[conv]/ret.75(YOLOX::nndct_conv2d_37)
        self.module_38 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/BaseConv[conv1]/ReLU[act]/27959(YOLOX::nndct_relu_38)
        self.module_39 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.79(YOLOX::nndct_depthwise_conv2d_39)
        self.module_40 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/27987(YOLOX::nndct_relu_40)
        self.module_41 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.83(YOLOX::nndct_conv2d_41)
        self.module_42 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28015(YOLOX::nndct_relu_42)
        self.module_43 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/Add[sc_add]/ret.87(YOLOX::nndct_elemwise_add_43)
        self.module_44 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/BaseConv[conv1]/Conv2d[conv]/ret.89(YOLOX::nndct_conv2d_44)
        self.module_45 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/BaseConv[conv1]/ReLU[act]/28046(YOLOX::nndct_relu_45)
        self.module_46 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.93(YOLOX::nndct_depthwise_conv2d_46)
        self.module_47 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/28074(YOLOX::nndct_relu_47)
        self.module_48 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.97(YOLOX::nndct_conv2d_48)
        self.module_49 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28102(YOLOX::nndct_relu_49)
        self.module_50 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/Add[sc_add]/ret.101(YOLOX::nndct_elemwise_add_50)
        self.module_51 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/Cat[cat]/ret.103(YOLOX::nndct_concat_51)
        self.module_52 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv3]/Conv2d[conv]/ret.105(YOLOX::nndct_conv2d_52)
        self.module_53 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark3]/Q_CSPLayer[1]/BaseConv[conv3]/ReLU[act]/28137(YOLOX::nndct_relu_53)
        self.module_54 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.109(YOLOX::nndct_depthwise_conv2d_54)
        self.module_55 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/DWConv[0]/BaseConv[dconv]/ReLU[act]/28165(YOLOX::nndct_relu_55)
        self.module_56 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.113(YOLOX::nndct_conv2d_56)
        self.module_57 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/DWConv[0]/BaseConv[pconv]/ReLU[act]/28193(YOLOX::nndct_relu_57)
        self.module_58 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv1]/Conv2d[conv]/ret.117(YOLOX::nndct_conv2d_58)
        self.module_59 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv1]/ReLU[act]/28221(YOLOX::nndct_relu_59)
        self.module_60 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv2]/Conv2d[conv]/ret.121(YOLOX::nndct_conv2d_60)
        self.module_61 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv2]/ReLU[act]/28249(YOLOX::nndct_relu_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.125(YOLOX::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/28277(YOLOX::nndct_relu_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.129(YOLOX::nndct_depthwise_conv2d_64)
        self.module_65 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/28305(YOLOX::nndct_relu_65)
        self.module_66 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.133(YOLOX::nndct_conv2d_66)
        self.module_67 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28333(YOLOX::nndct_relu_67)
        self.module_68 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[0]/Add[sc_add]/ret.137(YOLOX::nndct_elemwise_add_68)
        self.module_69 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/BaseConv[conv1]/Conv2d[conv]/ret.139(YOLOX::nndct_conv2d_69)
        self.module_70 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/BaseConv[conv1]/ReLU[act]/28364(YOLOX::nndct_relu_70)
        self.module_71 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.143(YOLOX::nndct_depthwise_conv2d_71)
        self.module_72 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/28392(YOLOX::nndct_relu_72)
        self.module_73 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.147(YOLOX::nndct_conv2d_73)
        self.module_74 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28420(YOLOX::nndct_relu_74)
        self.module_75 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[1]/Add[sc_add]/ret.151(YOLOX::nndct_elemwise_add_75)
        self.module_76 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/BaseConv[conv1]/Conv2d[conv]/ret.153(YOLOX::nndct_conv2d_76)
        self.module_77 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/BaseConv[conv1]/ReLU[act]/28451(YOLOX::nndct_relu_77)
        self.module_78 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.157(YOLOX::nndct_depthwise_conv2d_78)
        self.module_79 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/28479(YOLOX::nndct_relu_79)
        self.module_80 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.161(YOLOX::nndct_conv2d_80)
        self.module_81 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28507(YOLOX::nndct_relu_81)
        self.module_82 = py_nndct.nn.Add() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Sequential[m]/Q_Bottleneck[2]/Add[sc_add]/ret.165(YOLOX::nndct_elemwise_add_82)
        self.module_83 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/Cat[cat]/ret.167(YOLOX::nndct_concat_83)
        self.module_84 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv3]/Conv2d[conv]/ret.169(YOLOX::nndct_conv2d_84)
        self.module_85 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark4]/Q_CSPLayer[1]/BaseConv[conv3]/ReLU[act]/28542(YOLOX::nndct_relu_85)
        self.module_86 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=128, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.173(YOLOX::nndct_depthwise_conv2d_86)
        self.module_87 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/DWConv[0]/BaseConv[dconv]/ReLU[act]/28570(YOLOX::nndct_relu_87)
        self.module_88 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.177(YOLOX::nndct_conv2d_88)
        self.module_89 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/DWConv[0]/BaseConv[pconv]/ReLU[act]/28598(YOLOX::nndct_relu_89)
        self.module_90 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/BaseConv[conv1]/Conv2d[conv]/ret.181(YOLOX::nndct_conv2d_90)
        self.module_91 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/BaseConv[conv1]/ReLU[act]/28626(YOLOX::nndct_relu_91)
        self.module_92 = py_nndct.nn.MaxPool2d(kernel_size=[5, 5], stride=[1, 1], padding=[2, 2], dilation=[1, 1], ceil_mode=False) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/MaxPool2d[m]/ModuleList[0]/28641(YOLOX::nndct_maxpool_92)
        self.module_93 = py_nndct.nn.MaxPool2d(kernel_size=[9, 9], stride=[1, 1], padding=[4, 4], dilation=[1, 1], ceil_mode=False) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/MaxPool2d[m]/ModuleList[1]/28657(YOLOX::nndct_maxpool_93)
        self.module_94 = py_nndct.nn.MaxPool2d(kernel_size=[13, 13], stride=[1, 1], padding=[6, 6], dilation=[1, 1], ceil_mode=False) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/MaxPool2d[m]/ModuleList[2]/28673(YOLOX::nndct_maxpool_94)
        self.module_95 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/Cat[cat]/ret.185(YOLOX::nndct_concat_95)
        self.module_96 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/BaseConv[conv2]/Conv2d[conv]/ret.187(YOLOX::nndct_conv2d_96)
        self.module_97 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_SPPBottleneck[1]/BaseConv[conv2]/ReLU[act]/28706(YOLOX::nndct_relu_97)
        self.module_98 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv1]/Conv2d[conv]/ret.191(YOLOX::nndct_conv2d_98)
        self.module_99 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv1]/ReLU[act]/28734(YOLOX::nndct_relu_99)
        self.module_100 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv2]/Conv2d[conv]/ret.195(YOLOX::nndct_conv2d_100)
        self.module_101 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv2]/ReLU[act]/28762(YOLOX::nndct_relu_101)
        self.module_102 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.199(YOLOX::nndct_conv2d_102)
        self.module_103 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/28790(YOLOX::nndct_relu_103)
        self.module_104 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=128, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.203(YOLOX::nndct_depthwise_conv2d_104)
        self.module_105 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/28818(YOLOX::nndct_relu_105)
        self.module_106 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.207(YOLOX::nndct_conv2d_106)
        self.module_107 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/28846(YOLOX::nndct_relu_107)
        self.module_108 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/Cat[cat]/ret.211(YOLOX::nndct_concat_108)
        self.module_109 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv3]/Conv2d[conv]/ret.213(YOLOX::nndct_conv2d_109)
        self.module_110 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/CSPDarknet[backbone]/Sequential[dark5]/Q_CSPLayer[2]/BaseConv[conv3]/ReLU[act]/28878(YOLOX::nndct_relu_110)
        self.module_111 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/BaseConv[lateral_conv0]/Conv2d[conv]/ret.217(YOLOX::nndct_conv2d_111)
        self.module_112 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/BaseConv[lateral_conv0]/ReLU[act]/28910(YOLOX::nndct_relu_112)
        self.module_113 = py_nndct.nn.Interpolate() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Upsample[upsample]/ret.221(YOLOX::nndct_resize_113)
        self.module_114 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Cat[cat_f0]/ret.223(YOLOX::nndct_concat_114)
        self.module_115 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv1]/Conv2d[conv]/ret.225(YOLOX::nndct_conv2d_115)
        self.module_116 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv1]/ReLU[act]/28948(YOLOX::nndct_relu_116)
        self.module_117 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv2]/Conv2d[conv]/ret.229(YOLOX::nndct_conv2d_117)
        self.module_118 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv2]/ReLU[act]/28976(YOLOX::nndct_relu_118)
        self.module_119 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.233(YOLOX::nndct_conv2d_119)
        self.module_120 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/29004(YOLOX::nndct_relu_120)
        self.module_121 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.237(YOLOX::nndct_depthwise_conv2d_121)
        self.module_122 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/29032(YOLOX::nndct_relu_122)
        self.module_123 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.241(YOLOX::nndct_conv2d_123)
        self.module_124 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/29060(YOLOX::nndct_relu_124)
        self.module_125 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/Cat[cat]/ret.245(YOLOX::nndct_concat_125)
        self.module_126 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv3]/Conv2d[conv]/ret.247(YOLOX::nndct_conv2d_126)
        self.module_127 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p4]/BaseConv[conv3]/ReLU[act]/29092(YOLOX::nndct_relu_127)
        self.module_128 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/BaseConv[reduce_conv1]/Conv2d[conv]/ret.251(YOLOX::nndct_conv2d_128)
        self.module_129 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/BaseConv[reduce_conv1]/ReLU[act]/29120(YOLOX::nndct_relu_129)
        self.module_130 = py_nndct.nn.Interpolate() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Upsample[upsample]/ret.255(YOLOX::nndct_resize_130)
        self.module_131 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Cat[cat_f1]/ret.257(YOLOX::nndct_concat_131)
        self.module_132 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv1]/Conv2d[conv]/ret.259(YOLOX::nndct_conv2d_132)
        self.module_133 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv1]/ReLU[act]/29158(YOLOX::nndct_relu_133)
        self.module_134 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv2]/Conv2d[conv]/ret.263(YOLOX::nndct_conv2d_134)
        self.module_135 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv2]/ReLU[act]/29186(YOLOX::nndct_relu_135)
        self.module_136 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.267(YOLOX::nndct_conv2d_136)
        self.module_137 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/29214(YOLOX::nndct_relu_137)
        self.module_138 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=32, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.271(YOLOX::nndct_depthwise_conv2d_138)
        self.module_139 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/29242(YOLOX::nndct_relu_139)
        self.module_140 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.275(YOLOX::nndct_conv2d_140)
        self.module_141 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/29270(YOLOX::nndct_relu_141)
        self.module_142 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/Cat[cat]/ret.279(YOLOX::nndct_concat_142)
        self.module_143 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv3]/Conv2d[conv]/ret.281(YOLOX::nndct_conv2d_143)
        self.module_144 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_p3]/BaseConv[conv3]/ReLU[act]/29302(YOLOX::nndct_relu_144)
        self.module_145 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv2]/BaseConv[dconv]/Conv2d[conv]/ret.285(YOLOX::nndct_depthwise_conv2d_145)
        self.module_146 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv2]/BaseConv[dconv]/ReLU[act]/29330(YOLOX::nndct_relu_146)
        self.module_147 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv2]/BaseConv[pconv]/Conv2d[conv]/ret.289(YOLOX::nndct_conv2d_147)
        self.module_148 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv2]/BaseConv[pconv]/ReLU[act]/29358(YOLOX::nndct_relu_148)
        self.module_149 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Cat[cat_p1]/ret.293(YOLOX::nndct_concat_149)
        self.module_150 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv1]/Conv2d[conv]/ret.295(YOLOX::nndct_conv2d_150)
        self.module_151 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv1]/ReLU[act]/29390(YOLOX::nndct_relu_151)
        self.module_152 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv2]/Conv2d[conv]/ret.299(YOLOX::nndct_conv2d_152)
        self.module_153 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv2]/ReLU[act]/29418(YOLOX::nndct_relu_153)
        self.module_154 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.303(YOLOX::nndct_conv2d_154)
        self.module_155 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/29446(YOLOX::nndct_relu_155)
        self.module_156 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.307(YOLOX::nndct_depthwise_conv2d_156)
        self.module_157 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/29474(YOLOX::nndct_relu_157)
        self.module_158 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.311(YOLOX::nndct_conv2d_158)
        self.module_159 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/29502(YOLOX::nndct_relu_159)
        self.module_160 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/Cat[cat]/ret.315(YOLOX::nndct_concat_160)
        self.module_161 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv3]/Conv2d[conv]/ret.317(YOLOX::nndct_conv2d_161)
        self.module_162 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n3]/BaseConv[conv3]/ReLU[act]/29534(YOLOX::nndct_relu_162)
        self.module_163 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=128, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv1]/BaseConv[dconv]/Conv2d[conv]/ret.321(YOLOX::nndct_depthwise_conv2d_163)
        self.module_164 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv1]/BaseConv[dconv]/ReLU[act]/29562(YOLOX::nndct_relu_164)
        self.module_165 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv1]/BaseConv[pconv]/Conv2d[conv]/ret.325(YOLOX::nndct_conv2d_165)
        self.module_166 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/DWConv[bu_conv1]/BaseConv[pconv]/ReLU[act]/29590(YOLOX::nndct_relu_166)
        self.module_167 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Cat[cat_p0]/ret.329(YOLOX::nndct_concat_167)
        self.module_168 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv1]/Conv2d[conv]/ret.331(YOLOX::nndct_conv2d_168)
        self.module_169 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv1]/ReLU[act]/29622(YOLOX::nndct_relu_169)
        self.module_170 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv2]/Conv2d[conv]/ret.335(YOLOX::nndct_conv2d_170)
        self.module_171 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv2]/ReLU[act]/29650(YOLOX::nndct_relu_171)
        self.module_172 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/Conv2d[conv]/ret.339(YOLOX::nndct_conv2d_172)
        self.module_173 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/BaseConv[conv1]/ReLU[act]/29678(YOLOX::nndct_relu_173)
        self.module_174 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=128, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/Conv2d[conv]/ret.343(YOLOX::nndct_depthwise_conv2d_174)
        self.module_175 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[dconv]/ReLU[act]/29706(YOLOX::nndct_relu_175)
        self.module_176 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/Conv2d[conv]/ret.347(YOLOX::nndct_conv2d_176)
        self.module_177 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Sequential[m]/Q_Bottleneck[0]/DWConv[conv2]/BaseConv[pconv]/ReLU[act]/29734(YOLOX::nndct_relu_177)
        self.module_178 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/Cat[cat]/ret.351(YOLOX::nndct_concat_178)
        self.module_179 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv3]/Conv2d[conv]/ret.353(YOLOX::nndct_conv2d_179)
        self.module_180 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOPAFPN[backbone]/Q_CSPLayer[C3_n4]/BaseConv[conv3]/ReLU[act]/29766(YOLOX::nndct_relu_180)
        self.module_181 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[0]/Conv2d[conv]/ret.357(YOLOX::nndct_conv2d_181)
        self.module_182 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[0]/ReLU[act]/29798(YOLOX::nndct_relu_182)
        self.module_183 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.361(YOLOX::nndct_depthwise_conv2d_183)
        self.module_184 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[0]/BaseConv[dconv]/ReLU[act]/29826(YOLOX::nndct_relu_184)
        self.module_185 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.365(YOLOX::nndct_conv2d_185)
        self.module_186 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[0]/BaseConv[pconv]/ReLU[act]/29854(YOLOX::nndct_relu_186)
        self.module_187 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.369(YOLOX::nndct_depthwise_conv2d_187)
        self.module_188 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[1]/BaseConv[dconv]/ReLU[act]/29882(YOLOX::nndct_relu_188)
        self.module_189 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.373(YOLOX::nndct_conv2d_189)
        self.module_190 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[0]/DWConv[1]/BaseConv[pconv]/ReLU[act]/29910(YOLOX::nndct_relu_190)
        self.module_191 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[cls_preds]/ModuleList[0]/ret.377(YOLOX::nndct_conv2d_191)
        self.module_192 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.379(YOLOX::nndct_depthwise_conv2d_192)
        self.module_193 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[0]/BaseConv[dconv]/ReLU[act]/29958(YOLOX::nndct_relu_193)
        self.module_194 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.383(YOLOX::nndct_conv2d_194)
        self.module_195 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[0]/BaseConv[pconv]/ReLU[act]/29986(YOLOX::nndct_relu_195)
        self.module_196 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.387(YOLOX::nndct_depthwise_conv2d_196)
        self.module_197 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[1]/BaseConv[dconv]/ReLU[act]/30014(YOLOX::nndct_relu_197)
        self.module_198 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.391(YOLOX::nndct_conv2d_198)
        self.module_199 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[0]/DWConv[1]/BaseConv[pconv]/ReLU[act]/30042(YOLOX::nndct_relu_199)
        self.module_200 = py_nndct.nn.Conv2d(in_channels=64, out_channels=4, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[reg_preds]/ModuleList[0]/ret.395(YOLOX::nndct_conv2d_200)
        self.module_201 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[obj_preds]/ModuleList[0]/ret.397(YOLOX::nndct_conv2d_201)
        self.module_202 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOXHead[head]/Cat[cat_list]/ModuleList[0]/ret.399(YOLOX::nndct_concat_202)
        self.module_203 = py_nndct.nn.dequant_output() #YOLOX::YOLOX/YOLOXHead[head]/DeQuantStub[quant_outs]/ModuleList[0]/30087(YOLOX::nndct_dequant_stub_203)
        self.module_204 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[1]/Conv2d[conv]/ret.403(YOLOX::nndct_conv2d_204)
        self.module_205 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[1]/ReLU[act]/30118(YOLOX::nndct_relu_205)
        self.module_206 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.407(YOLOX::nndct_depthwise_conv2d_206)
        self.module_207 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[0]/BaseConv[dconv]/ReLU[act]/30146(YOLOX::nndct_relu_207)
        self.module_208 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.411(YOLOX::nndct_conv2d_208)
        self.module_209 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[0]/BaseConv[pconv]/ReLU[act]/30174(YOLOX::nndct_relu_209)
        self.module_210 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.415(YOLOX::nndct_depthwise_conv2d_210)
        self.module_211 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[1]/BaseConv[dconv]/ReLU[act]/30202(YOLOX::nndct_relu_211)
        self.module_212 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.419(YOLOX::nndct_conv2d_212)
        self.module_213 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[1]/DWConv[1]/BaseConv[pconv]/ReLU[act]/30230(YOLOX::nndct_relu_213)
        self.module_214 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[cls_preds]/ModuleList[1]/ret.423(YOLOX::nndct_conv2d_214)
        self.module_215 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.425(YOLOX::nndct_depthwise_conv2d_215)
        self.module_216 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[0]/BaseConv[dconv]/ReLU[act]/30278(YOLOX::nndct_relu_216)
        self.module_217 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.429(YOLOX::nndct_conv2d_217)
        self.module_218 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[0]/BaseConv[pconv]/ReLU[act]/30306(YOLOX::nndct_relu_218)
        self.module_219 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.433(YOLOX::nndct_depthwise_conv2d_219)
        self.module_220 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[1]/BaseConv[dconv]/ReLU[act]/30334(YOLOX::nndct_relu_220)
        self.module_221 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.437(YOLOX::nndct_conv2d_221)
        self.module_222 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[1]/DWConv[1]/BaseConv[pconv]/ReLU[act]/30362(YOLOX::nndct_relu_222)
        self.module_223 = py_nndct.nn.Conv2d(in_channels=64, out_channels=4, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[reg_preds]/ModuleList[1]/ret.441(YOLOX::nndct_conv2d_223)
        self.module_224 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[obj_preds]/ModuleList[1]/ret.443(YOLOX::nndct_conv2d_224)
        self.module_225 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOXHead[head]/Cat[cat_list]/ModuleList[1]/ret.445(YOLOX::nndct_concat_225)
        self.module_226 = py_nndct.nn.dequant_output() #YOLOX::YOLOX/YOLOXHead[head]/DeQuantStub[quant_outs]/ModuleList[1]/30407(YOLOX::nndct_dequant_stub_226)
        self.module_227 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[2]/Conv2d[conv]/ret.449(YOLOX::nndct_conv2d_227)
        self.module_228 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/BaseConv[stems]/ModuleList[2]/ReLU[act]/30438(YOLOX::nndct_relu_228)
        self.module_229 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.453(YOLOX::nndct_depthwise_conv2d_229)
        self.module_230 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[0]/BaseConv[dconv]/ReLU[act]/30466(YOLOX::nndct_relu_230)
        self.module_231 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.457(YOLOX::nndct_conv2d_231)
        self.module_232 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[0]/BaseConv[pconv]/ReLU[act]/30494(YOLOX::nndct_relu_232)
        self.module_233 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.461(YOLOX::nndct_depthwise_conv2d_233)
        self.module_234 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[1]/BaseConv[dconv]/ReLU[act]/30522(YOLOX::nndct_relu_234)
        self.module_235 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.465(YOLOX::nndct_conv2d_235)
        self.module_236 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[cls_convs]/ModuleList[2]/DWConv[1]/BaseConv[pconv]/ReLU[act]/30550(YOLOX::nndct_relu_236)
        self.module_237 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[cls_preds]/ModuleList[2]/ret.469(YOLOX::nndct_conv2d_237)
        self.module_238 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[0]/BaseConv[dconv]/Conv2d[conv]/ret.471(YOLOX::nndct_depthwise_conv2d_238)
        self.module_239 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[0]/BaseConv[dconv]/ReLU[act]/30598(YOLOX::nndct_relu_239)
        self.module_240 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[0]/BaseConv[pconv]/Conv2d[conv]/ret.475(YOLOX::nndct_conv2d_240)
        self.module_241 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[0]/BaseConv[pconv]/ReLU[act]/30626(YOLOX::nndct_relu_241)
        self.module_242 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=64, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[1]/BaseConv[dconv]/Conv2d[conv]/ret.479(YOLOX::nndct_depthwise_conv2d_242)
        self.module_243 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[1]/BaseConv[dconv]/ReLU[act]/30654(YOLOX::nndct_relu_243)
        self.module_244 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[1]/BaseConv[pconv]/Conv2d[conv]/ret.483(YOLOX::nndct_conv2d_244)
        self.module_245 = py_nndct.nn.ReLU(inplace=True) #YOLOX::YOLOX/YOLOXHead[head]/Sequential[reg_convs]/ModuleList[2]/DWConv[1]/BaseConv[pconv]/ReLU[act]/30682(YOLOX::nndct_relu_245)
        self.module_246 = py_nndct.nn.Conv2d(in_channels=64, out_channels=4, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[reg_preds]/ModuleList[2]/ret.487(YOLOX::nndct_conv2d_246)
        self.module_247 = py_nndct.nn.Conv2d(in_channels=64, out_channels=1, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOX::YOLOX/YOLOXHead[head]/Conv2d[obj_preds]/ModuleList[2]/ret.489(YOLOX::nndct_conv2d_247)
        self.module_248 = py_nndct.nn.Cat() #YOLOX::YOLOX/YOLOXHead[head]/Cat[cat_list]/ModuleList[2]/ret.491(YOLOX::nndct_concat_248)
        self.module_249 = py_nndct.nn.dequant_output() #YOLOX::YOLOX/YOLOXHead[head]/DeQuantStub[quant_outs]/ModuleList[2]/30727(YOLOX::nndct_dequant_stub_249)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(input=output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_0 = self.module_6(output_module_0)
        output_module_0 = self.module_7(output_module_0)
        output_module_8 = self.module_8(output_module_0)
        output_module_8 = self.module_9(output_module_8)
        output_module_10 = self.module_10(output_module_0)
        output_module_10 = self.module_11(output_module_10)
        output_module_12 = self.module_12(output_module_8)
        output_module_12 = self.module_13(output_module_12)
        output_module_12 = self.module_14(output_module_12)
        output_module_12 = self.module_15(output_module_12)
        output_module_12 = self.module_16(output_module_12)
        output_module_12 = self.module_17(output_module_12)
        output_module_12 = self.module_18(input=output_module_12, other=output_module_8, alpha=1)
        output_module_12 = self.module_19(dim=1, tensors=[output_module_12,output_module_10])
        output_module_12 = self.module_20(output_module_12)
        output_module_12 = self.module_21(output_module_12)
        output_module_12 = self.module_22(output_module_12)
        output_module_12 = self.module_23(output_module_12)
        output_module_12 = self.module_24(output_module_12)
        output_module_12 = self.module_25(output_module_12)
        output_module_26 = self.module_26(output_module_12)
        output_module_26 = self.module_27(output_module_26)
        output_module_28 = self.module_28(output_module_12)
        output_module_28 = self.module_29(output_module_28)
        output_module_30 = self.module_30(output_module_26)
        output_module_30 = self.module_31(output_module_30)
        output_module_30 = self.module_32(output_module_30)
        output_module_30 = self.module_33(output_module_30)
        output_module_30 = self.module_34(output_module_30)
        output_module_30 = self.module_35(output_module_30)
        output_module_30 = self.module_36(input=output_module_30, other=output_module_26, alpha=1)
        output_module_37 = self.module_37(output_module_30)
        output_module_37 = self.module_38(output_module_37)
        output_module_37 = self.module_39(output_module_37)
        output_module_37 = self.module_40(output_module_37)
        output_module_37 = self.module_41(output_module_37)
        output_module_37 = self.module_42(output_module_37)
        output_module_37 = self.module_43(input=output_module_37, other=output_module_30, alpha=1)
        output_module_44 = self.module_44(output_module_37)
        output_module_44 = self.module_45(output_module_44)
        output_module_44 = self.module_46(output_module_44)
        output_module_44 = self.module_47(output_module_44)
        output_module_44 = self.module_48(output_module_44)
        output_module_44 = self.module_49(output_module_44)
        output_module_44 = self.module_50(input=output_module_44, other=output_module_37, alpha=1)
        output_module_44 = self.module_51(dim=1, tensors=[output_module_44,output_module_28])
        output_module_44 = self.module_52(output_module_44)
        output_module_44 = self.module_53(output_module_44)
        output_module_54 = self.module_54(output_module_44)
        output_module_54 = self.module_55(output_module_54)
        output_module_54 = self.module_56(output_module_54)
        output_module_54 = self.module_57(output_module_54)
        output_module_58 = self.module_58(output_module_54)
        output_module_58 = self.module_59(output_module_58)
        output_module_60 = self.module_60(output_module_54)
        output_module_60 = self.module_61(output_module_60)
        output_module_62 = self.module_62(output_module_58)
        output_module_62 = self.module_63(output_module_62)
        output_module_62 = self.module_64(output_module_62)
        output_module_62 = self.module_65(output_module_62)
        output_module_62 = self.module_66(output_module_62)
        output_module_62 = self.module_67(output_module_62)
        output_module_62 = self.module_68(input=output_module_62, other=output_module_58, alpha=1)
        output_module_69 = self.module_69(output_module_62)
        output_module_69 = self.module_70(output_module_69)
        output_module_69 = self.module_71(output_module_69)
        output_module_69 = self.module_72(output_module_69)
        output_module_69 = self.module_73(output_module_69)
        output_module_69 = self.module_74(output_module_69)
        output_module_69 = self.module_75(input=output_module_69, other=output_module_62, alpha=1)
        output_module_76 = self.module_76(output_module_69)
        output_module_76 = self.module_77(output_module_76)
        output_module_76 = self.module_78(output_module_76)
        output_module_76 = self.module_79(output_module_76)
        output_module_76 = self.module_80(output_module_76)
        output_module_76 = self.module_81(output_module_76)
        output_module_76 = self.module_82(input=output_module_76, other=output_module_69, alpha=1)
        output_module_76 = self.module_83(dim=1, tensors=[output_module_76,output_module_60])
        output_module_76 = self.module_84(output_module_76)
        output_module_76 = self.module_85(output_module_76)
        output_module_86 = self.module_86(output_module_76)
        output_module_86 = self.module_87(output_module_86)
        output_module_86 = self.module_88(output_module_86)
        output_module_86 = self.module_89(output_module_86)
        output_module_86 = self.module_90(output_module_86)
        output_module_86 = self.module_91(output_module_86)
        output_module_92 = self.module_92(output_module_86)
        output_module_93 = self.module_93(output_module_86)
        output_module_94 = self.module_94(output_module_86)
        output_module_95 = self.module_95(dim=1, tensors=[output_module_86,output_module_92,output_module_93,output_module_94])
        output_module_95 = self.module_96(output_module_95)
        output_module_95 = self.module_97(output_module_95)
        output_module_98 = self.module_98(output_module_95)
        output_module_98 = self.module_99(output_module_98)
        output_module_100 = self.module_100(output_module_95)
        output_module_100 = self.module_101(output_module_100)
        output_module_98 = self.module_102(output_module_98)
        output_module_98 = self.module_103(output_module_98)
        output_module_98 = self.module_104(output_module_98)
        output_module_98 = self.module_105(output_module_98)
        output_module_98 = self.module_106(output_module_98)
        output_module_98 = self.module_107(output_module_98)
        output_module_98 = self.module_108(dim=1, tensors=[output_module_98,output_module_100])
        output_module_98 = self.module_109(output_module_98)
        output_module_98 = self.module_110(output_module_98)
        output_module_98 = self.module_111(output_module_98)
        output_module_98 = self.module_112(output_module_98)
        output_module_113 = self.module_113(input=output_module_98, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_113 = self.module_114(dim=1, tensors=[output_module_113,output_module_76])
        output_module_115 = self.module_115(output_module_113)
        output_module_115 = self.module_116(output_module_115)
        output_module_117 = self.module_117(output_module_113)
        output_module_117 = self.module_118(output_module_117)
        output_module_115 = self.module_119(output_module_115)
        output_module_115 = self.module_120(output_module_115)
        output_module_115 = self.module_121(output_module_115)
        output_module_115 = self.module_122(output_module_115)
        output_module_115 = self.module_123(output_module_115)
        output_module_115 = self.module_124(output_module_115)
        output_module_115 = self.module_125(dim=1, tensors=[output_module_115,output_module_117])
        output_module_115 = self.module_126(output_module_115)
        output_module_115 = self.module_127(output_module_115)
        output_module_115 = self.module_128(output_module_115)
        output_module_115 = self.module_129(output_module_115)
        output_module_130 = self.module_130(input=output_module_115, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_130 = self.module_131(dim=1, tensors=[output_module_130,output_module_44])
        output_module_132 = self.module_132(output_module_130)
        output_module_132 = self.module_133(output_module_132)
        output_module_134 = self.module_134(output_module_130)
        output_module_134 = self.module_135(output_module_134)
        output_module_132 = self.module_136(output_module_132)
        output_module_132 = self.module_137(output_module_132)
        output_module_132 = self.module_138(output_module_132)
        output_module_132 = self.module_139(output_module_132)
        output_module_132 = self.module_140(output_module_132)
        output_module_132 = self.module_141(output_module_132)
        output_module_132 = self.module_142(dim=1, tensors=[output_module_132,output_module_134])
        output_module_132 = self.module_143(output_module_132)
        output_module_132 = self.module_144(output_module_132)
        output_module_145 = self.module_145(output_module_132)
        output_module_145 = self.module_146(output_module_145)
        output_module_145 = self.module_147(output_module_145)
        output_module_145 = self.module_148(output_module_145)
        output_module_145 = self.module_149(dim=1, tensors=[output_module_145,output_module_115])
        output_module_150 = self.module_150(output_module_145)
        output_module_150 = self.module_151(output_module_150)
        output_module_152 = self.module_152(output_module_145)
        output_module_152 = self.module_153(output_module_152)
        output_module_150 = self.module_154(output_module_150)
        output_module_150 = self.module_155(output_module_150)
        output_module_150 = self.module_156(output_module_150)
        output_module_150 = self.module_157(output_module_150)
        output_module_150 = self.module_158(output_module_150)
        output_module_150 = self.module_159(output_module_150)
        output_module_150 = self.module_160(dim=1, tensors=[output_module_150,output_module_152])
        output_module_150 = self.module_161(output_module_150)
        output_module_150 = self.module_162(output_module_150)
        output_module_163 = self.module_163(output_module_150)
        output_module_163 = self.module_164(output_module_163)
        output_module_163 = self.module_165(output_module_163)
        output_module_163 = self.module_166(output_module_163)
        output_module_163 = self.module_167(dim=1, tensors=[output_module_163,output_module_98])
        output_module_168 = self.module_168(output_module_163)
        output_module_168 = self.module_169(output_module_168)
        output_module_170 = self.module_170(output_module_163)
        output_module_170 = self.module_171(output_module_170)
        output_module_168 = self.module_172(output_module_168)
        output_module_168 = self.module_173(output_module_168)
        output_module_168 = self.module_174(output_module_168)
        output_module_168 = self.module_175(output_module_168)
        output_module_168 = self.module_176(output_module_168)
        output_module_168 = self.module_177(output_module_168)
        output_module_168 = self.module_178(dim=1, tensors=[output_module_168,output_module_170])
        output_module_168 = self.module_179(output_module_168)
        output_module_168 = self.module_180(output_module_168)
        output_module_181 = self.module_181(output_module_132)
        output_module_181 = self.module_182(output_module_181)
        output_module_183 = self.module_183(output_module_181)
        output_module_183 = self.module_184(output_module_183)
        output_module_183 = self.module_185(output_module_183)
        output_module_183 = self.module_186(output_module_183)
        output_module_183 = self.module_187(output_module_183)
        output_module_183 = self.module_188(output_module_183)
        output_module_183 = self.module_189(output_module_183)
        output_module_183 = self.module_190(output_module_183)
        output_module_183 = self.module_191(output_module_183)
        output_module_192 = self.module_192(output_module_181)
        output_module_192 = self.module_193(output_module_192)
        output_module_192 = self.module_194(output_module_192)
        output_module_192 = self.module_195(output_module_192)
        output_module_192 = self.module_196(output_module_192)
        output_module_192 = self.module_197(output_module_192)
        output_module_192 = self.module_198(output_module_192)
        output_module_192 = self.module_199(output_module_192)
        output_module_200 = self.module_200(output_module_192)
        output_module_201 = self.module_201(output_module_192)
        output_module_200 = self.module_202(dim=1, tensors=[output_module_200,output_module_201,output_module_183])
        output_module_200 = self.module_203(input=output_module_200)
        output_module_204 = self.module_204(output_module_150)
        output_module_204 = self.module_205(output_module_204)
        output_module_206 = self.module_206(output_module_204)
        output_module_206 = self.module_207(output_module_206)
        output_module_206 = self.module_208(output_module_206)
        output_module_206 = self.module_209(output_module_206)
        output_module_206 = self.module_210(output_module_206)
        output_module_206 = self.module_211(output_module_206)
        output_module_206 = self.module_212(output_module_206)
        output_module_206 = self.module_213(output_module_206)
        output_module_206 = self.module_214(output_module_206)
        output_module_215 = self.module_215(output_module_204)
        output_module_215 = self.module_216(output_module_215)
        output_module_215 = self.module_217(output_module_215)
        output_module_215 = self.module_218(output_module_215)
        output_module_215 = self.module_219(output_module_215)
        output_module_215 = self.module_220(output_module_215)
        output_module_215 = self.module_221(output_module_215)
        output_module_215 = self.module_222(output_module_215)
        output_module_223 = self.module_223(output_module_215)
        output_module_224 = self.module_224(output_module_215)
        output_module_223 = self.module_225(dim=1, tensors=[output_module_223,output_module_224,output_module_206])
        output_module_223 = self.module_226(input=output_module_223)
        output_module_168 = self.module_227(output_module_168)
        output_module_168 = self.module_228(output_module_168)
        output_module_229 = self.module_229(output_module_168)
        output_module_229 = self.module_230(output_module_229)
        output_module_229 = self.module_231(output_module_229)
        output_module_229 = self.module_232(output_module_229)
        output_module_229 = self.module_233(output_module_229)
        output_module_229 = self.module_234(output_module_229)
        output_module_229 = self.module_235(output_module_229)
        output_module_229 = self.module_236(output_module_229)
        output_module_229 = self.module_237(output_module_229)
        output_module_238 = self.module_238(output_module_168)
        output_module_238 = self.module_239(output_module_238)
        output_module_238 = self.module_240(output_module_238)
        output_module_238 = self.module_241(output_module_238)
        output_module_238 = self.module_242(output_module_238)
        output_module_238 = self.module_243(output_module_238)
        output_module_238 = self.module_244(output_module_238)
        output_module_238 = self.module_245(output_module_238)
        output_module_246 = self.module_246(output_module_238)
        output_module_247 = self.module_247(output_module_238)
        output_module_246 = self.module_248(dim=1, tensors=[output_module_246,output_module_247,output_module_229])
        output_module_246 = self.module_249(input=output_module_246)
        return (output_module_200,output_module_223,output_module_246)
